/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:ee56d882-ae1a-49f2-904d-c683fbf1725d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_2ogzXfOW9",
    "aws_user_pools_web_client_id": "1m45oeepbde2egsqr0dtll69tt",
    "oauth": {
        "domain": "lasvittennis-auth-prod.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://lasvittennis.com/account/",
        "redirectSignOut": "https://lasvittennis.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://6yhtbas6lnhd3nel3r4fr4oqni.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
