/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c17b45ae-761c-4746-a7f5-acee207a69cc",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_uvQWviMBM",
    "aws_user_pools_web_client_id": "5i33glqg9uvmj05ic7edgpkusj",
    "oauth": {
        "domain": "lasvittennis6c503e44-6c503e44-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://7mmvmslrqzdxxnqallxwewkide.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
