/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:3135e1df-c709-4896-a917-f23530183f3c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_5gMi7o5vS",
    "aws_user_pools_web_client_id": "4kges0mn9n2je6v1s30h2ndtg1",
    "oauth": {
        "domain": "lasvittennis-auth-deploy.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://lasvittennis.com/account/",
        "redirectSignOut": "https://lasvittennis.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://sdgqsyalbre47fhlszej3q4tjq.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
