export const actionKeys = {
  SET_LOADING: "app/SET_LOADING",
  GET_CLIENT_DETAIL_REQUEST: "client/GET_CLIENT_DETAIL_REQUEST",
  GET_CLIENT_DETAIL_SUCCESS: "client/GET_CLIENT_DETAIL_SUCCESS",
  CLIENT_SIGN_IN: "client/CLIENT_SIGN_IN",
  CLIENT_SIGN_OUT: "client/CLIENT_SIGN_OUT",
  FETCH_BILLING_LIST_REQUEST: "api/FETCH_BILLING_LIST_REQUEST",
  FETCH_BILLING_LIST_SUCCESS: "api/FETCH_BILLING_LIST_SUCCESS",
  CREATE_BILLING_REQUEST: "api/CREATE_BILLING_REQUEST",
};

export const FederationTypes = {
  GOOGLE: "Google",
  FACEBOOK: "Facebook",
};
