export const actionKeys = {
  SET_LOADING: "app/SET_LOADING",
  SET_LANGUAGE: "app/SET_LANGUAGE",
  GET_CLIENT_DETAIL_REQUEST: "client/GET_CLIENT_DETAIL_REQUEST",
  GET_CLIENT_DETAIL_SUCCESS: "client/GET_CLIENT_DETAIL_SUCCESS",
  CLIENT_SIGN_IN: "client/CLIENT_SIGN_IN",
  CLIENT_SIGN_OUT: "client/CLIENT_SIGN_OUT",
  CLIENT_CUSTOM_LOGIN_FAIL: "client/CLIENT_CUSTOM_LOGIN_FAIL",
  CLIENT_CUSTOM_SIGN_IN: "client/CLIENT_CUSTOM_SIGN_IN",
  CLIENT_CUSTOM_SIGN_UP: "client/CLIENT_CUSTOM_SIGN_UP",
  CLIENT_CUSTOM_CONFIRM_SIGN_UP: "client/CLIENT_CUSTOM_CONFIRM_SIGN_UP",
  CLIENT_CUSTOM_FORGOTPASSWORD: "client/CLIENT_CUSTOM_FORGOTPASSWORD",
  CLIENT_CUSTOM_FORGOTPASSWORD_SUBMIT:
    "client/CLIENT_CUSTOM_FORGOTPASSWORD_SUBMIT",
  LOGIN_MODAL: "client/LOGIN_MODAL",
  FETCH_BILLING_LIST_REQUEST: "api/FETCH_BILLING_LIST_REQUEST",
  FETCH_BILLING_LIST_SUCCESS: "api/FETCH_BILLING_LIST_SUCCESS",
  CREATE_BILLING_REQUEST: "api/CREATE_BILLING_REQUEST",
  PAYLOAD_MODAL: "api/PAYLOAD_MODAL",
};

export const FederationTypes = {
  GOOGLE: "Google",
  FACEBOOK: "Facebook",
};
